# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_promotion:
    resources:
        catalog_promotion:
            classes:
                model: Sylius\Component\Core\Model\CatalogPromotion
        catalog_promotion_scope:
            classes:
                model: Sylius\Component\Core\Model\CatalogPromotionScope
        promotion_subject:
            classes:
                model: "%sylius.model.order.class%"
        promotion:
            classes:
                model: Sylius\Component\Core\Model\Promotion
                repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\PromotionRepository
        promotion_coupon:
            classes:
                model: Sylius\Component\Core\Model\PromotionCoupon
                repository: Sylius\Bundle\PromotionBundle\Doctrine\ORM\PromotionCouponRepository

    catalog_promotion_scope:
        validation_groups:
            for_products:
                - 'sylius'
                - 'sylius_catalog_promotion_scope_for_products'
            for_variants:
                - 'sylius'
                - 'sylius_catalog_promotion_scope_for_variants'
            for_taxons:
                - 'sylius'
                - 'sylius_catalog_promotion_scope_for_taxons'
