framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
        # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_FAIL)%'

        routing:
            'Sylius\Component\Promotion\Event\CatalogPromotionUpdated': async
            'Sylius\Component\Promotion\Event\CatalogPromotionEnded': async

        default_bus: sylius.command_bus
        buses:
            sylius.command_bus: &command_bus
                middleware:
                    - 'validation'
                    - 'doctrine_transaction'
            sylius.event_bus: &event_bus
                default_middleware: allow_no_handlers
            sylius_default.bus: *command_bus
            sylius_event.bus: *event_bus
        
