winzou_state_machine:
    sylius_catalog_promotion:
        class: "%sylius.model.catalog_promotion.class%"
        property_path: state
        graph: sylius_catalog_promotion
        state_machine_class: "%sylius.state_machine.class%"
        states:
            inactive: ~
            processing: ~
            active: ~
            failed: ~
        transitions:
            process:
                from: [inactive, active]
                to: processing
            activate:
                from: [processing]
                to: active
            deactivate:
                from: [processing, active]
                to: inactive
            fail:
                from: [processing]
                to: failed
